### ISSUE TITLE
error: invalid types 'int[int]' for array subscript  ptrSharedMemory[row][colum]=255;

### ISSUE THREAD

**Issue by lietochris** [lietochris/Paralelo#5]
https://github.com/lietochris/Paralelo/blob/adae9ab5300eaba88ebfc0eeae5dcebc801518aa/memoriaCompartida/PrimoRelativo.cpp#L64

error: invalid types 'int[int]' for array subscript
                     ptrSharedMemory[row][colum]=255;

**Comment by lietochris** [comment]
No puedes guardar una matriz en memoria compartida, en este caso solo los procesos deben hacer el trabajo, no guardar nada en memoria.

**Comment by SirZempo** [comment]
Entonces, solo lo dejo como un vector y ahí guardo la operación?

**Comment by lietochris** [comment]
Segun tengo entendido, no tienes que guardar nada solo llenar los datos.

**Comment by SirZempo** [comment]
Vale voy a cambiar eso en un momento y ahorita lo vuelvo a guardar.
